apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ice-cream
  name: ice-cream
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: ice-cream
  type: NodePort
status:
  loadBalancer: {}
