apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: first-depoy
  name: first-depoy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first-depoy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: first-depoy
    spec:
      containers:
      - image: rajeshjindal911/declarative_pipeline:latest
        name: declarative-pipeline-slsbv
        resources: {}
status: {}
