apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: gallery
  name: gallery
spec:
  containers:
  - image: rajeshjindal911/declarative_pipeline:latest
    name: gallery
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
