apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-loadbalancer
  annotations: 
        service.beta.kubernetes.io/aws-load-balancer-type: "external"  # Specifies an external ALB/NLB
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  type: NodePort
