apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: myrepo
  name: testsvc
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: myrepo
  type: NodePort
status:
  loadBalancer: {}
